### ISSUE TITLE
Would you please set this repository to private?

### ISSUE THREAD

**Issue by xf3227** [derekbarbosa/ec440#1]
Dear derekbarbosa, I hope this message finds you well. At the behest of the EC440 instructors, we kindly request that you set this repository to private. By making the content accessible, there's a potential risk of compromising academic integrity for students currently enrolled in the course. We appreciate your understanding and prompt attention to this matter.

**Comment by derekbarbosa** [comment]
Hi.

Apologies. I had it temporarily set to public while searching for employment around the time I took the course.

I'll set it now. Thanks for the note.
